export enum QUERYKEYS {
  aboutus = 'abouts',
  contactus = 'contactus',
  allBooks = 'allBooks',
  allauthors = 'allauthors',
  book = 'book',
  authors = 'authors',
  categories = 'categories',
  libraries = 'libraries',
  librarycategories = 'librarycategories',
  allBorrowedBooks = 'borrowed-books',
  homepage = 'homepage',
  allfeedback = 'allfeedback',
  feedback = 'feedback',
  pendingtestimonial = 'pendingtestimonial',
  acceptedtestimonial = 'acceptedtestimonial',
  alloffers = 'alloffers',
  allusers = 'allusers',
  report = 'report',
}
